//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes.Models
{
  using System;
  using System.ComponentModel;

  public partial class Notes
  {
    public int Id { get; set; }
    public Nullable<int> UserId { get; set; }

    [DisplayName("Ýçerik")]
    public string Content { get; set; }
  }
}
