//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes.Models
{
  using System.ComponentModel;
  using System.ComponentModel.DataAnnotations;

  public partial class Users
  {
    public int Id { get; set; }

    [DisplayName("Kullanýcý Adý")]
    [Required(ErrorMessage = "Bu alan gereklidir.")]
    public string Username { get; set; }

    [DisplayName("Þifre")]
    [DataType(DataType.Password)]
    [Required(ErrorMessage = "Bu alan gereklidir.")]
    public string Password { get; set; }

    [DisplayName("Þifre(tekrar)")]
    [DataType(DataType.Password)]
    [System.ComponentModel.DataAnnotations.CompareAttribute("Password", ErrorMessage = "Þifre eþleþmiyor.")]
    public string PasswordConfirm { get; set; }
    public string LoginErrorMessage { get; internal set; }
  }
}
